config/routes.rb
Rails.application.routes.draw do

  root :to => 'links#index'
  resources :links, :except => [:show]
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
    @referring_link_id = params[:referring_link_id]
    @referring_comment_id = params[:referring_comment_id]
    if @referring_link_id != nil
      @commentable_id = @referring_link_id
      @commentable_type = "Link"
    end
    if @referring_comment_id != nil
      @commentable_id = @referring_comment_id
      @commentable_type = "Comment"
    end
  end

  def create

    @comment = Comment.new(comment_params)
    link = Link.find(params[:referring_link_id]) if params[:referring_link_id] != nil
    referring_comment = Comment.find(params[:referring_comment_id]) if params[:referring_comment_id] != nil
    if @comment.save
      link.comments << @comment if params[:referring_link_id]
      @comment.comments << referring_comment if params[:referring_comment_id]
      flash[:notice] = "Comment created."
      redirect_to links_path
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(comment_params)
    if @comment.update(params[:comment])
      flash[:notice] = "Comment updated."
      redirect_to links_path
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment deleted."
    redirect_to links_path
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :commentable_id,
                                    :commentable_type)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      flash[:notice] = "Link created."
      redirect_to links_path
    else
      render 'new'
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      flash[:notice] = "Link updated."
      redirect_to links_path
    else
      render 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:notice] = "Link deleted."
    redirect_to links_path
  end

  private
  def link_params
    params.require(:link).permit(:link, :vote, :rating, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <div class="form-group">
    <%= f.hidden_field :referring_link_id, :value => @referring_link_id %>
    <%= f.hidden_field :referring_comment_id, :value => @referring_comment_id %>
    <%= f.hidden_field :commentable_id, :value => @commentable_id %>
    <%= f.hidden_field :commentable_type, :value => @commentable_type %>
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>
  <%= f.submit(:class => "btn btn-danger") %>
<% end %>

app/views/comments/new.html.erb
<h1> Add a Comment </h1>

<hr>

<%= render 'form' %>
<br>
<%= link_to "Cancel", links_path, :class=> "btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>
    <% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/links/_comment.html.erb
<ul>
    <% comments_to_display.each do |comment| %>
      <li><%= "#{comment[:comment]}" %>
        <%= link_to "Add Comment", new_comment_path(:referring_comment_id => comment.id) %>
        <%= link_to "Edit",edit_comment_path(comment) %>
        <%= link_to "Delete", comment_path(comment), :data => {:confirm => "You sure?", :method => "delete"} %>
      </li>
      <% if comment.comments != nil %>
        <%= render partial: "comment", locals: { comments_to_display: comment.comments } %>
      <% end %>
    <% end %>
</ul>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>
  <div class="form-group">
    <%= f.label :vote %>
    <%= f.text_field :vote %>
  </div>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>
  <%= f.submit(:class => "btn btn-danger") %>
<% end %>

app/views/links/edit.html.erb
<h1> Edit a Link </h1>

<hr>

<%= render 'form' %>
<br>
<%= link_to "Cancel", links_path, :class=> "btn btn-success" %>

app/views/links/index.html.erb
<h1>Links</h1>
<ul>
  <% @links.each do |link| %>
    <br>
    <li><%= "#{link.link} - #{link.vote} - #{link.date}" %>
        <%= link_to "Add Comment", new_comment_path(:referring_link_id => link.id) %>
        <%= link_to "Edit",edit_link_path(link) %>
        <%= link_to "Delete", link_path(link), :data => {:confirm => "You sure?", :method => "delete"} %>
    </li>
    <%= render partial: "comment", locals: { comments_to_display: link.comments } %>
  <% end %>
</ul>
<br>
<%= link_to "New Link", new_link_path, :class=> "btn btn-success" %>

app/views/links/new.html.erb
<h1> Add a Link </h1>

<hr>

<%= render 'form' %>
<br>
<%= link_to "Cancel", links_path, :class=> "btn btn-success" %>